/* Copies the woff2 faces out of the @fontsource packages into
 * src/renderer/fonts/ and writes the @font-face block that uses them.
 * Runs from `npm install` (postinstall), so a packaged build never
 * reaches out to a font CDN at runtime.
 * Amanorsac Studio Master Standard §3 — "Ship fonts locally". */
import { mkdirSync, copyFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, '..', 'src', 'renderer', 'fonts');
const modules = join(here, '..', 'node_modules');

const WANT = [
  { family: 'Inter',            pkg: '@fontsource/inter',            weights: [400, 500, 600, 700] },
  { family: 'JetBrains Mono',   pkg: '@fontsource/jetbrains-mono',   weights: [400, 500, 600] },
  { family: 'Barlow Condensed', pkg: '@fontsource/barlow-condensed', weights: [600, 700] }
];

mkdirSync(out, { recursive: true });
const css = [
  '/* Generated by scripts/copy-fonts.mjs — do not edit by hand. */'
];
let copied = 0, missing = [];

for (const { family, pkg, weights } of WANT) {
  const slug = pkg.split('/')[1];
  for (const w of weights) {
    const src = join(modules, pkg, 'files', `${slug}-latin-${w}-normal.woff2`);
    const file = `${slug}-${w}.woff2`;
    if (!existsSync(src)) { missing.push(`${family} ${w}`); continue; }
    copyFileSync(src, join(out, file));
    copied++;
    css.push(
      `@font-face{font-family:"${family}";src:url("${file}") format("woff2");` +
      `font-weight:${w};font-style:normal;font-display:swap}`
    );
  }
}

if (copied === 0) {
  console.warn('[chordlight] no font files found — leaving the system fallback in place');
} else {
  writeFileSync(join(out, 'fonts.css'), css.join('\n') + '\n');
  console.log(`[chordlight] bundled ${copied} font files`);
  if (missing.length) console.warn('[chordlight] missing faces:', missing.join(', '));
}
